#pragma once

#define MAX_FPS 60

#define CELL_SIZE 20

#define WIDTH_IN_CELLS 40
#define HEIGHT_IN_CELLS 35

#define SCREEN_WIDTH (WIDTH_IN_CELLS * CELL_SIZE)
#define SCREEN_HEIGHT (HEIGHT_IN_CELLS * CELL_SIZE)
